site_name: CSC 106
docs_dir: Notes
theme_dir: theme
site_url: http://uvicnotes.github.io/CSC-106/
repo_url: https://github.com/UVicNotes/CSC-106
site_description: Course Notes for CSC 106 - The Practice of Computer Science
site_author: Dominique Charlebois
pages:
- Home: 'index.md'
- Notes:
    - Lecture:
        - 'Introduction': 'Lecture/1-Introduction.md'
        - 'Databases': 'Lecture/2-Databases.md'
        - 'Flowcharts': 'Lecture/3-Flowcharts.md'
        - 'Number Systems': 'Lecture/4-Number-Systems.md'
        - 'Guest 1': 'Lecture/5-Guest1.md'
        - 'Logic': 'Lecture/6-Logic.md'
        - 'Guest 2 - SWU': 'Lecture/7-Guest2.md'
        - 'Software Development and Software Engineering': 'Lecture/8-Software-Dev-&-Software-Eng.md'
        - 'Guest 3 - HCI': 'Lecture/9-Guest3.md'
        - 'Artificial Intelligence and Data Mining': 'Lecture/10-Artificial-Intelligence-&-Data-Mining.md'
        - 'Guest 4 - The Reading Brain': 'Lecture/11-The-Reading-Brain.md'
        - 'Python': 'Lecture/12-Python-Programming.md'
        - 'Guest 5 - Computer Applications': 'Lecture/13-Guest5.md'
        - 'Guest 6 - Programming Languages': 'Lecture/14-Guest6.md'
        - 'Guest 7 - Cryptography': 'Lecture/15-Guest7.md'
        - 'Recursion': 'Lecture/16-Recursion.md'
        - 'Guest 8 - Game Dev': 'Lecture/17-Guest8.md'
        - 'Graph': 'Lecture/18-Graph.md'
    - Lab:
        - 'Lab': 'Lab/Lab.md'
    - Annex:
        - 'Announcements': 'Annex/Announcements.md'
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.rawgit.com/UVicNotes/UVicNotes/81099952ba789829fab1840e5d26cb5a2bf62011/helpers/mathjax.js
markdown_extensions:
    - mdx_math
extra:
  version: 'Spring 2017'
  palette:
    primary: 'purple'
    accent: 'green'
  author:
    github: 'flytewizard'