site_name: CSC 106
docs_dir: Notes
theme_dir: theme
site_url: http://uvicnotes.github.io/CSC-106/
repo_url: https://github.com/UVicNotes/CSC-106
site_description: Course Notes for CSC 106 - The Practice of Computer Science
site_author: Dominique Charlebois
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.rawgit.com/UVicNotes/UVicNotes/81099952ba789829fab1840e5d26cb5a2bf62011/helpers/mathjax.js
markdown_extensions:
    - mdx_math
extra:
  version: 'Spring 2017'
  palette:
    primary: 'purple'
    accent: 'green'
  author: 
    github: 'flytewizard'